package com.sysadmindoc.alarmclock.util

import com.sysadmindoc.alarmclock.data.update.UpdateChecker
import org.junit.Assert.assertEquals
import org.junit.Test

class ReleaseBodyTest {
    @Test fun fullChangelogLineIsDropped() {
        val body = "**Full Changelog**: https://github.com/anurag008w/AlarmClockXtreme/compare/v1.16.5...v1.16.6"
        assertEquals(listOf("See the full release notes on GitHub."), UpdateChecker.bodyToBullets(body))
    }

    @Test fun realBulletsSurviveWithMarkdownStripped() {
        val body = "- News: articles show a **picture**\n- See [the docs](https://example.com/x) now\n\nFull changelog: https://github.com/a/b/compare/v1...v2\n"
        assertEquals(
            listOf("News: articles show a picture", "See the docs now"),
            UpdateChecker.bodyToBullets(body)
        )
    }

    @Test fun autoGeneratedAuthorSuffixIsTrimmed() {
        val body = "* Fix crash on start by @someone in https://github.com/a/b/pull/9"
        assertEquals(listOf("Fix crash on start"), UpdateChecker.bodyToBullets(body))
    }
}
